// <auto-generated />
using FARegistryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FARegistryAPI.Migrations
{
    [DbContext(typeof(RegistryContext))]
    partial class RegistryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FARegistryAPI.Models.RegistryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthDateDatedeauth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectiveDateDateenvigueur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryDateDatedexpire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FederalStakeholders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatitudeLatitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lespartiesprenantesfed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lespartiesprenantesprov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationDescAutreinfogeo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongitudeLongitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ouvrageprincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATHNoNoduSAPH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescDescduprojet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromoteurOrganisme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProponentOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceTerritoire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceTerritory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvincialStakeholders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RGION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistryContactduRegistre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleTitre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typedeauthorization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLdecontact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatershedNomduBassin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
